#+title: ROS2 Humble Development Container
#+author: Atri Hegde

* Preface

* Instructions
** Setting up VSCode (Optional)

You can just write your code in your preferred code editor directly from your ros2 workspace, but if you work with VSCode you can install the Dev Containers extension to connect to the ros2 docker container, so you can open terminals directly from vscode without having to run =ros_shell=.

** Linux

Thankfully, you don't need to run docker-compose on linux, as everything runs "natively" from the =Dockerfile=. We can just use the following command to build and create the container.

#+begin_src bash

#+end_src

And this to get its shell.

#+begin_src bash

#+end_src

#+begin_quote
Since you use Linux I am expecting you to be familiar enough with the terminal to setup your own aliases.
#+end_quote

** MacOS


*** setup.bash
Run the provided =setup.bash= everytime you want to work on ROS or

1. Find out what shell you are using by running the command =echo $SHELL=.
2. It will be either bash or zsh.
   a. If you are running =bash= add the next code block to =~/.bashrc=
   b. If you are running =zsh= add the the next code block to =~/.zshrc=

#+begin_src bash
ros_dev() {
  if (( $# % 2 != 0 )); then
    echo "Usage: ros_dev <container_name1> <project_path1> [<container_name2> <project_path2> ...]"
    return 1
  fi

  while (( $# >= 2 )); do
    ROS_DEV_CONTAINER_NAME=$1
    ROS_PROJECT_PATH=$2
    shift 2

    cd "$ROS2_DOCKER_DIR" && docker-compose up -d --build
  done
}

ros_shell() {
    if (( $# != 1 )); then
        echo "Usuage: ros_shell <container_name>"
        return 1
    fi

    docker exec -it $1 /bin/zsh
}
#+end_src


** Windows

** Setting up environment variables

Set the following in either your =.envrc= using =direnv=. If you have not heard of =direnv=, we can just add it to our =.bashrc= file (or =.zshrc= if you are using zsh).

*** ROS2_DOCKER_DIR

We need to have

#+begin_src bash
export ROS2_DOCKER_ENV="/path/to/this/repository"
#+end_src

You can test if it worked by using this command and seeing the correct path as the output.

#+begin_src bash
echo $ROS2_DOCKER_ENV
#+end_src
